### ISSUE TITLE
The blog url disfunctions now.

### ISSUE THREAD

**Issue by JiaxiangBU** [tinyheero/tinyheero.github.io#1]
![image](https://user-images.githubusercontent.com/15884785/48110985-35285500-e28a-11e8-90f9-b996176917ac.png)

**Comment by tinyheero** [comment]
Works for me and several others that I have asked to check. It might be an firewall issue on your end.

**Comment by JiaxiangBU** [comment]
Yes, I retry to browse it, it works now, thanks for your reply.
